name: Deploy to hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: 8.3
      - name: Install Packages
        run: composer install --no-dev
      - name: Deploy to Server
        uses: ngocquyhoang/laravel-deploy@laravel-custom-port
        with:
          host: ${{secrets.CLINIC_HOST}}
          user: ${{secrets.CLINIC_USER}}
          path: ${{secrets.CLINIC_PATH}}
          owner: ${{secrets.CLINIC_OWNER}}
#        env:
#          APP_URL: https://clinic-dev.proviant-pay.ru/

