name: Deploy to hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    name: Check project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure SSH
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1
        with:
          host: https://progressrb.ru:1500
          port:
          user: root
          key: ${{ HOST_PRIVATE_KEY }}
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: check
    steps:
#      - name: Install dependencies
#        run: composer update
      - name: Test request
        uses: octokit/request-action@v2.x
        with:
          route: GET https://clinic-dev.proviant-pay.ru/api/test
        env:
          GITHUB_TOKEN: ${{ secrets.CLINIC_GIT_TOKEN}}
#      - uses: appleboy/git-push-action@v0.0.3
#        with:
#          remote:
#      - uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{secrets.CLINIC_HOST}}
#          port: ${{secrets.CLINIC_PORT}}
#          username: ${{secrets.CLINIC_USER}}
#          key: ${{secrets.CLINIC_SSH}}
#          script: "cd /var/www/html && ./.scripts/deploy.sh"


#        env:
#          APP_URL: https://clinic-dev.proviant-pay.ru/

