name: Deploy to hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Test request
        uses: octokit/request-action@v2.x
        with:
          route: GET /test
#      - uses: appleboy/git-push-action@v0.0.3
#        with:
#          remote:
#      - uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{secrets.CLINIC_HOST}}
#          port: ${{secrets.CLINIC_PORT}}
#          username: ${{secrets.CLINIC_USER}}
#          key: ${{secrets.CLINIC_SSH}}
          script: "cd /var/www/html && ./.scripts/deploy.sh"


#        env:
#          APP_URL: https://clinic-dev.proviant-pay.ru/

